// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Exercise struct {
	ID         int64
	Name       string
	TargetArea sql.NullString
}

type Session struct {
	Token  interface{}
	Data   []byte
	Expiry interface{}
}

type User struct {
	StytchID   string
	DatabaseID string
	Created    string
}
